baseURL = "https://gocnhintoancanh.netlify.app/"
languageCode = "vi"
title = "Góc Nhìn Toàn Cảnh"

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

# ===============================
# MARKUP
# ===============================
[markup]

  # ---- Markdown renderer ----
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  # ---- TOC (Jump link cho Google) ----
  [markup.tableOfContents]
    startLevel = 2   # h2
    endLevel   = 3   # h3
    ordered    = false

# ===============================
# SECURITY
# ===============================
[security]
  enableInlineShortcodes = true

  [security.exec]
    allow = ['^dart-sass$', '^go$', '^npx$', '^postcss$', '^tailwindcss$']

  [security.http]
    methods = ['GET']
    urls = ['https://unpkg.com', 'http://localhost:8081']
