baseURL = "https://gocnhintoancanh.netlify.app/"
languageCode = "vi"
title = "Góc Nhìn Toàn Cảnh"

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "SITEMAP"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
